os: windows
language: shell

script:
  - choco install python3
  - PATH="C:\\Python37:C:\\Python37\\Scripts:$PATH"
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8, 'bits')\""
  - python -m pip --version
  - python -m pip install -U pip
  - python -m pip --version
  - python -m pip install -r requirements.txt
