os: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip list"
  - "echo ----- NEW VENV -----"
  - ps: "Measure Command { python -m venv v} "
  - "v\\Scripts\\python -m pip install -U pip"
  - "v\\Scripts\\pip --version"
  - "v\\Scripts\\pip list"
  - ps: "Measure-Command {v\\Scripts\\pip install -r requirements.txt}"
  - "v\\Scripts\\pip list"
