os: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m venv v"
  - "v\\Scripts\\activate.bat"
  - "python -m pip install -U pip"
  - "python -m pip install -r requirements.txt"