os: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: "Measure-Command { python -m venv v } "
  - "v\\Scripts\\activate.bat"
  - ps: "Measure-Command {v\\Scripts\\pip install -r requirements.txt}"
  - "v\\Scripts\\pip list"
