os: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build_script:
  - "set"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip list"
  - ps: "Measure-Command { python -m venv v --copies} "
  - "v\\Scripts\\activate.bat"
  - "v\\Scripts\\python -m pip install -U pip"
  - "v\\Scripts\\pip --version"
  - "v\\Scripts\\pip list"
  - ps: "Measure-Command {v\\Scripts\\pip install -r requirements.txt}"
  - "v\\Scripts\\pip list"
