trigger:
- master

jobs:
- job: bench
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - script: |
      python -m pip install -U pip
      python -m pip --version
      python -m venv v
