trigger:
- master

jobs:
- job: scenario-1 # Disable Windows Defender, pre-install PIP 18.x create environment only.
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - powershell: |
      Set-MpPreference -DisableRealtimeMonitoring $true
    displayName: Disable Windows Defender real-time scanning
  - script: |
      python -m pip install -U pip
      python -m pip --version
    displayName: Update PIP.
  - script: |
      python -m venv A
    displayName: Create environment
- job: scenario-2 # Disable Windows Defender, pre-install PIP 18.x create environment and install dependencies.
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - powershell: |
      Set-MpPreference -DisableRealtimeMonitoring $true
    displayName: Disable Windows Defender real-time scanning
  - script: |
      python -m pip install -U pip
      python -m pip --version
    displayName: Update PIP.
  - script: |
      python -m venv A
    displayName: Create environment
  - script: |
      python -m venv A
      C\Scripts\activate.bat
      python -m pip install -r requirements.txt
    displayName: Activate and install dependencies.
