trigger:
- master

jobs:
- job: prep
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - task: PowerShell@2
    inputs:
      filePath: install.ps1
      arguments: -CacheVenv
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: cache
      targetPath: $(Build.SourcesDirectory)
- job: use
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - task: PowerShell@2
    inputs:
      filePath: install.ps1
      arguments: -UseVenv