trigger:
- master

jobs:
- job: bench
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - powershell: |
      measure-command { python -m pip install -U pip }
      measure-command { python -m pip --version }
      measure-command { python -m venv v }
      get-childitem v
