trigger:
- master

jobs:
- job: bench
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - powershell: |
      # Set-MpPreference -DisableRealtimeMonitoring $true
    displayName: Disable Windows Defender real-time scanning
  - script: |
      python -m pip install -U pip
      python -m pip --version
    displayName: Update PIP.
  - script: |
      python -m venv A
    displayName: Create environment first time (A)
  - script: |
      python -m venv B
    displayName: Create environment second time (B)
  - script: |
      python -m venv C
      C\Scripts\activate.bat
      python -m pip install -r requirements.txt
    displayName: Create environment third time (C) and add dependencies
  - script: |
      A\Scripts\activate.bat
      python -m pip install -r requirements.txt
    displayName: Activate existing environment (A) and add dependencies
