trigger:
- master

jobs:
- job: bench
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - powershell: |
      # Set-MpPreference -DisableRealtimeMonitoring $true
    displayName: Disable Windows Defender real-time scanning
  - powershell: |
      python -m pip install -U pip
      python -m pip --version
    displayName: Update PIP.
  - powershell: |
      python -m venv X
    displayName: Create environment X.
  - powershell: |
      python -m venv Y
    displayName: Create environment  Y
  - powershell: |
      python -m venv Z
    displayName: Create environment Z
